In [2]:
import numpy as np
from celmech.disturbing_function import df_coefficient_Ctilde
from celmech.disturbing_function import evaluate_df_coefficient_dict

In [57]:
def Mprime(alpha, m):
    m1, m2, m3 = m
    m_tot = m1+m2+m3
    b1=evaluate_df_coefficient_dict({(0,(1.5, 1,0)):1},alpha)
    b2=evaluate_df_coefficient_dict({(0,(1.5, 2,0)):1},alpha)
    
    R = np.array([[np.sqrt(m1/m_tot), np.sqrt(m2/m_tot), np.sqrt(m3/m_tot)],
             [-np.sqrt(m3/(m1+m3)), 0, np.sqrt(m1/(m1+m3))],
             [np.sqrt(m1*m2/(m1+m3)/m_tot), -np.sqrt((m1+m3)/m_tot), np.sqrt(m2*m3/(m1+m3)/m_tot)]])
    M = np.array([[b1*(m2+m3), -b2*np.sqrt(m1*m2), -b2*np.sqrt(m1*m3)],
             [-b2*np.sqrt(m1*m2), b1*(m1+m3), -b2*np.sqrt(m2*m3)],
             [-b2*np.sqrt(m1*m3), -b2*np.sqrt(m2*m3), b1*(m1+m2)]])*(-alpha)*2*np.pi/4
    
    print(f"eccentricity matrix =")
    print(M)
    
    return np.matmul(np.matmul(R, M), np.transpose(R))

In [59]:
Mprime(0.995, (1e-7, 1e-7, 1e-7))

eccentricity matrix =
[[-0.00797948  0.00398898  0.00398898]
 [ 0.00398898 -0.00797948  0.00398898]
 [ 0.00398898  0.00398898 -0.00797948]]


array([[-1.51638763e-06,  2.59456378e-19, -2.04298800e-19],
       [ 2.39414733e-19, -1.19684664e-02, -1.35330262e-19],
       [-2.45023798e-19,  1.00366551e-19, -1.19684664e-02]])

In [60]:
# Two-body case

def test(alpha, mass):
    m1, m2 = mass
    b1=evaluate_df_coefficient_dict({(0,(1.5, 1,0)):1},alpha)
    b2=evaluate_df_coefficient_dict({(0,(1.5, 2,0)):1},alpha)
    M = np.array([[alpha**(1/2)*b1*m2, -alpha**(3/4)*b2*np.sqrt(m1*m2)],
                 [-alpha**(3/4)*b2*np.sqrt(m1*m2), alpha*b1*m1]])*(2*np.pi)/4
    print(M)

In [61]:
test(0.995, (1e-4, 1e-4))

[[ 3.99975345 -3.99398521]
 [-3.99398521  3.98974153]]
